# Generated by Django 5.1 on 2025-04-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='features',
            field=models.TextField(blank=True, help_text='Festures for pricing, seperated by new line', null=True),
        ),
    ]
