# Generated by Django 5.1 on 2025-04-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_subscriptionprice_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='features',
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Festures for pricing, seperated by new line', null=True),
        ),
    ]
