name: 1 - Hello World GitHub actions

on:
  workflow_dispatch: # Manually trigger the action
  # schedule:
  #   - cron: '30 15 * * *'
  # push: # git push
  #   branch:
  #     - main # branch to trigger the action

jobs:
  hello:
    runs-on: ubuntu-latest # OS to run the action on
    steps:
      - name: Hello World
        run: echo "Hello World!"